server:
   port: 8000
spring:
   datasource:
          url: jdbc:sqlserver://localhost:1433;databaseName=DeskBookDev;encrypt=true;trustServerCertificate=true
          username: sa
          password: Admin#123
   jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #dialect: org.hibernate.dialect.SQLServerDialect
            
